# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demol' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  # Pods for demol

  target 'demolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demolUITests' do
    # Pods for testing
  end

end
